### ISSUE TITLE
How to use this on Heroku with redis-cloud?

### ISSUE THREAD

**Issue by bonbonio** [lemonde/primus-cluster#17]
I want to share the primus sockets across multiple heroku dynos.

Below is what I added to my node app, which was running with one dyno, I added the following, and i see logs of socket connections and messages incoming, but they don't seem to be broadcast out?

Also, any ideas how I can test this on a local machine?
- I added the redis, and the primus-cluster packages.
  
  var redis = require('redis');
  var PrimusCluster = require('primus-cluster');
  var url = require('url');
  var redisObject = url.parse(process.env.REDISCLOUD_URL);
  
  var primus = new Primus(server.listener, {
  transformer: 'engine.io',
  cluster: {
    redis: {
      port: redisObject.port,
      host: redisObject.host,
      connect_timeout: 200
    }
  }
  });
  
  primus.use('emitter', Emitter);
  primus.use('rooms', Rooms);
  primus.use('cluster', PrimusCluster);

**Comment by neoziro** [comment]
@varmint09 it should work, but you know this module only enable the broadcast.

**Comment by varmint09** [comment]
Hi, could you clarify that a bit more for me, very sorry!

What else do I need to use, I want to use rooms and emitter too – surely I cannot be the only one, or the first! 

many thanks

**Comment by neoziro** [comment]
@varmint09 the method `primus.send` will send a message to all people, but you can't see people of another server for an example.

**Comment by varmint09** [comment]
@neoziro not sure that helped me understand.

So I want to share sockets, which use rooms and emitter across a few heroku dynos... how do I approach this problem? I thought that if I used this plugin it would store the socket in redis so that all the node processes would carry out their emits/messages on all the connections made to the shared socket.

I don't quite understand why this seems to be so difficult, I cannot be the only use case?

Also, how do i pass through authorisation details for the redis process?

https://devcenter.heroku.com/articles/rediscloud#using-redis-from-node-js

I am not providing any auth details currently;

var client = redis.createClient(redisURL.port, redisURL.hostname, {no_ready_check: true});
client.auth(redisURL.auth.split(":")[1]);

How do I pass no_ready_check, and also call auth with primus-cluster*

* Assuming this module will actually do what I need? :(

**Comment by varmint09** [comment]
Seemingly, I can pass in auth details like so;

{ 
redis: { 
  port: redisURL.port, 
  host: redisURL.host, 
  auth: redisURL.auth.split(":")[1] 
  }
}

I'll try this later.

**Comment by gregberge** [comment]
Outdated
